# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: PresentPy

theme:
  name: material

nav:
  - Home: index.md
  - Supported content: supported-content.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences